/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_filltriangle_android_GL2JNILib */

#ifndef _Included_com_filltriangle_android_GL2JNILib
#define _Included_com_filltriangle_android_GL2JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_filltriangle_android_GL2JNILib
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_vstar_cameraplaydemo_ndk_ImageUtilEngine_initGL2
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_filltriangle_android_GL2JNILib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_vstar_cameraplaydemo_ndk_ImageUtilEngine_stepGL2
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif